---
- name: Load the OS specific variables
  tags: zfsnap
  include_vars: "{{ ansible_os_family }}.yml"

- name: Copy zfsnap script on server
  tags: zfsnap
  copy: src=zfSnap.sh dest=/usr/local/sbin/zfsnap.sh owner=root group=root mode=0700

- name: Create cron task for incremental backups
  tags: zfsnap
  cron:
    minute: "{{ item.zfsnap_minute|default('23') }}"
    hour: "{{ item.zfsnap_hour|default('01') }}"
    day: "{{ item.zfsnap_day|default('*') }}"
    month: "{{ item.zfsnap_month|default('*') }}"
    dow: "{{ item.zfsnap_dow|default('*') }}"
    user: "{{ item.zfsnap_user|default(zfsnap_user) }}"
    name: "{{ item.zfsnap_cron_file|default(zfsnap_cron_file) }}"
    cron_file: "{{ item.zfsnap_cron_file|default(zfsnap_cron_file) }}"
    job: "/usr/local/sbin/zfsnap.sh -a {{ item.zfsnap_ttl|default('1m') }} -r {{ item.zfsnap_backup_path|default('tank/vz') }}"
    backup: yes
    state: present
  with_items: "{{ zfsnap_jobs }}"

- name: Create cron task for deleting old backups
  tags: zfsnap
  cron:
    minute: 0
    hour: 1
    user: "{{ zfsnap_user|default(zfsnap_user) }}"
    name: "Delete backups"
    cron_file: "zfsnap_delete"
    job: "/usr/local/sbin/zfsnap.sh -d"
    backup: yes
    state: present
