---
- name: Load the OS specific variables
  tags: zfsnap
  include_vars: "{{ ansible_os_family }}.yml"

- name: Copy zfsnap script on server
  tags: zfsnap
  copy: src=zfSnap.sh dest=/usr/local/sbin/zfsnap.sh owner=root group=root mode=0700 

- name: Create cron task for incremental backups
  tags: zfsnap
  cron: minute=0 hour=0 user=root name="Create backups" cron_file="zfsnap" job="/usr/local/sbin/zfsnap.sh -a {{ zfsnap_backup_expiry }} -r tank/vz" backup=yes state=present

- name: Create cron task for deleting old backups
  tags: zfsnap
  cron: minute=0 hour=1 user=root name="Delete backups" cron_file="zfsnap_delete" job="/usr/local/sbin/zfsnap.sh -d" backup=yes state=present


